### ISSUE TITLE
Error "'module' object is not subscriptable" when using tft.print()

### ISSUE THREAD

**Issue by MiLeG** [boochow/MicroPython-ST7735#2]
Hi!
I am running this on an esp32 and every time I use the tft.print() function. I'm not that python savvy to identify the problem on my own, so here's the complete error log:
`
>>> tftprinttest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 103, in tftprinttest
  File "ST7735.py", line 174, in text
TypeError: 'module' object is not subscriptable
`
Thanks!

**Comment by MiLeG** [comment]
Okay, it was just a simple matter of bad font usage. Soldier on!
